### PR TITLE
Opener transport

### PR DESCRIPTION
**Pull request by bergie**
The other side of noflo/noflo-runtime-postmessage#3

### CODE REVIEW

**Comment by jonnor** [comment]
Do we have a way of testing this?

**Comment by bergie** [comment]
@jonnor right now fbp-protocol-client doesn't have tests for any other transports than MicroFlo (and WebRTC, but those are skipped). Would be good to add at least smoketests for `opener`, `iframe`, and `websocket`

**Comment by bergie** [comment]
In the meanwhile, I'm testing this manually:

* Build the test project of grunt-noflo-browser with noflo/grunt-noflo-browser#25 (set `ide` to `http://localhost:9999/index.html` in `Gruntfile.js`)
* Build noflo-ui locally with this patch applied to fbp-protocol-client
* Open the grunt-noflo-browser test project (`tmp/Clock.html`) in your browser. Click _Debug in Flowhub_

**Comment by jonnor** [comment]
Ok

**Comment by bergie** [comment]
Had couple of minor bugs in both ends, but now it basically works:

screenshot 2017-08-09 at 20 22 01

**Pull request merged**
