### PR TITLE
Set allow-forms permission for the iframe sandbox

### PR DESCRIPTION
**Pull request by bergie**
Fixes Flowhub React example

### CODE REVIEW

**Comment by bergie** [comment]
@jonnor currently build is failing due to microflo-empscripten issues. Would be nice to fix those

**Comment by jonnor** [comment]
Uhm, `cannot find module ws` - that is a very odd message. Is `fbp-manifest` or something including `microflo-runtime.js`. If so, why? That probably wont work

**Comment by jonnor** [comment]
@bergie ^ see above command

**Comment by bergie** [comment]
Both microflo and microflo-emscripten are in package deps https://github.com/flowbased/fbp-protocol-client/blob/master/package.json

**Comment by jonnor** [comment]
Problem is that `webpack` or something is failing on this third-party dep, which is deep inside some generated Emscripten code. It looks all be optional but I don't know how to disable it.
I don't see any other required deps which are not node.js standard though, so maybe just add `commonjs ws` so webpack does not fall over?

**Comment by jonnor** [comment]
Of course the issue with webpack is that this may be needed by every dependency down...

**Comment by jonnor** [comment]
The hacky way is of course to just include `ws`...

**Comment by jonnor** [comment]
Wait, let me try to remove some unused `#include` statements, maybe that will help Emscripten to not generate this code. It looks to be for standard I/O streams

**Comment by jonnor** [comment]
@bergie no luck, reduced includes to a minimum and still the `require('ws')` code is there

**Comment by jonnor** [comment]
@bergie do you want me to add `ws` as a dependency to `microflo-emscripten` in the meantime? It is actually very small, few subdeps, nothing native.

**Comment by jonnor** [comment]
The offending code is gone when compiling with latest Emscripten, but that is impossible to setup on Travis CI so not planning on that anytime soon...

**Comment by bergie** [comment]
@jonnor well, we need to get this back to releasable shape, so do whatever you must.

**Comment by bergie** [comment]
@jonnor next error: https://travis-ci.org/flowbased/fbp-protocol-client/builds/190673694#L390

**Comment by jonnor** [comment]
@bergie the `ws` dependency is now included, but it does not fix it because webpack does not look in subdirs. You need to use NPMv3. This will basically affect all projects using `grunt-noflo-browser` due to the webpack limitation...

**Comment by jonnor** [comment]
@bergie https://github.com/flowbased/fbp-protocol-client/pull/82

**Pull request merged**
